project:
  title: "Analysis"
  output-dir: docs
  render: 
    - "*.qmd"
    - "!old-r/"

format: 
    html:
        embed-resources: true
        title-block-banner: true
        theme: darkly
        toc: true
        toc-depth: 4