project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!old-r/"

website:
  title: "Analysis"
  navbar: 
    left:
      - fix_data.qmd
      - analysis.qmd


format: 
    html:
        embed-resources: true
        title-block-banner: true
        theme: darkly
        toc: true
        toc-depth: 4